name: Deploy Confluent Platform to Azure Kubernetes Service

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install az, authenticate to cluster, etc
        run: |
          ./az aks get-credentials \
               --resource-group {{secret.AZ_RG }} \
               --name {{secret.AKS_CLUSTER}} \
               --overwrite-existing
          ./deploy.sh
          
